
- name: PantryEvening
  entities:
    light.led_panel_bijkeuken:
        state: on
        kelvin: 2200
        brightness_pct: 40

- name: PantryDay
  entities:
    light.led_panel_bijkeuken:
        state: on
        kelvin: 2500
        brightness_pct: 100
