HOMEASSISTANT_DB="{{influxdb_homeassistant_db}}"
# SENSU_DB="{{influxdb_sensu_db}}"
PROMETHEUS_DB="{{influxdb_prometheus_db}}"
influxd backup -portable -database "$HOMEASSISTANT_DB" "$DIRECTORY/$HOMEASSISTANT_DB"
influxd backup -portable -database "$PROMETHEUS_DB" "$DIRECTORY/$PROMETHEUS_DB"
# influxd backup -database "$SENSU_DB" "$DIRECTORY/$SENSU_DB"