#########################################################################
# Grouping of light sources                                             #
#########################################################################

lights_downstairs:
  name: "Downstairs lights"
  entities:
   - light.woonkamer_tv
   - light.tv_staanlamp
   - light.living_room
   - light.dining_table
   - light.kitchen
   - light.office
   - switch.desk_lamp
   - switch.christmas_tree
   - switch.christmas_ambience_office

lights_downstairs_automatic:
  name: "Automatically controlled downstairs lights"
  entities:
    - light.living_ambience_lamp_1
    - light.office_ambience_lamp_1

lights_outside:
  name: "Lights outside"
  entities:
    - light.lamp_voordeur_1
    - light.garden

lights_upstairs:
  name: "Lights Upstairs"
  entities:
    - light.bathroom_group
    - light.nachttafel_ilse
    - light.nachttafel_joris
    - switch.bathroom_mirror_light
    # - light.laundry_room_lamp_1

# Entities that are allowed to be "unavailable".
# Used as part of sanity testing to ignore certain entities that are unavailable that are expected to be so sometimes.
unavailable_allowed:
  name: Unavailable allowed
  entities: # []
    - light.living_ambience_lamp_1

lights_christmas:
  name: "Christmas lights"
  entities:
    - switch.christmas_tree
    - switch.christmas_ambience_office