start_morning_tv:
  url: "http://{{groups["tv_controller"][0]}}:8000/show_url?url=http://{{casa_ip}}:{{homeassistant_port}}/lovelace/morning-tv"
  username: "{{tv_api_username}}"
  password: "{{tv_api_password}}"

gusto_navigate:
  url: "http://{{casa_ip}}:{{gusto_port}}/api/navigate"
  method: post
  headers:
    content-type: "application/json" 
  payload: '{"url": "http://{{casa_ip}}:{{appdaemon_port}}/LockScreen?skin=casa&returnURI=http://{{casa_ip}}:{{gusto_port}}"}'