- name: Installing {{service_name}} systemd service
  template: src=service.service dest=/etc/systemd/system/{{service_name}}.service
  notify:
    - daemon_reload
  become: yes

- name: Installing some convenience aliases
  template: src=service-aliases.sh dest=/etc/profile.d/{{service_shorthand}}-aliases.sh
  become: yes

- name: Start {{service_name}} service
  service: name={{service_name}} state=started enabled=yes
  become: yes